name: "Deployment"

on:
  workflow_call:
    inputs:
      version:
        description: "A version tag to deploy"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "A version tag to deploy"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release donwload ${{ inputs.version }} --pattern dist.tgz
          tar -xvzf dist.tgz --directory app
