name: "Release"

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  release:
    outputs:
      version: ${{ steps.versions.outputs.next }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      - name: Build
        run: |
          mkdir dist
          dd if=/dev/urandom of=dist/a.txt count=4 bs=1024
          dd if=/dev/urandom of=dist/b.txt count=4 bs=1024
          dd if=/dev/urandom of=dist/c.txt count=4 bs=1024
      - name: Verify release
        id: versions
        uses: ./actions/versions
      - name: Create release
        id: release
        if: ${{ steps.versions.outputs.next }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tar -cvzf dist.tgz dist
          gh release create "${{ steps.versions.outputs.next }}" dist.tgz

  deploy:
    if: ${{ needs.release.outputs.version }}
    needs: release
    uses: ./.github/workflows/deployment.yml
    with:
      version: ${{ needs.release.outputs.version }}
