name: "Release"

on:
  workflow_dispatch:
    branches: [main]

jobs:
  release:
    outputs:
      version: ${{ steps.release.outputs.version }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Create release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PREV_VERSION="$(git tag --merged main --sort=-version:refname || echo "")"
          NEXT_VERSION="v$(date +"%Y%m%d.%H.%M%S")"

          if [[ "${PREV_VERSION}" != "" ]]; then
            gh release create "${NEXT_VERSION}" --notes-start-tag "${PREV_VERSION}" --generate-notes
          else
            gh release create "${NEXT_VERSION}"
          fi

          echo "version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
  deploy:
    needs: release
    uses: ./.github/workflows/deployment.yml
    with:
      version: ${{ needs.release.outputs.version }}
